export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8">
        <div className="rounded-2xl bg-white p-8 shadow-sm sm:p-12">
          <h1 className="mb-3 text-center font-serif text-4xl font-medium text-gray-900 sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="mb-12 text-center font-sans text-sm text-gray-500">
            Last updated on 14-Oct-2024
          </p>

          <div className="space-y-8 font-sans">
            <p className="text-gray-700">
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You
              respond to our advertisements and tells You about Your privacy
              rights and how the law protects You. We use Your Personal Data to
              contact and support you, as well as to provide and improve the
              Service. By using the Service, You agree to the collection and use
              of information in accordance with this Privacy Policy.
            </p>

            <section className="space-y-6">
              <h2 className="font-serif text-2xl text-gray-900">
                Interpretation and Definitions
              </h2>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Interpretation
                </h3>
                <p className="text-gray-700">
                  The words of which the initial letter is capitalized have
                  meanings defined under the following conditions. The following
                  definitions shall have the same meaning regardless of whether
                  they appear in singular or in plural.
                </p>
              </div>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Definitions
                </h3>
                <p className="mb-4 text-gray-700">
                  For the purposes of this Privacy Policy:
                </p>
                <ul className="list-disc space-y-3 pl-6 text-gray-700">
                  <li>
                    <span className="font-medium">Company</span> (referred to as
                    either &quot;the Company&quot;, &quot;We&quot;,
                    &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers
                    to Supersquad.
                  </li>
                  <li>
                    <span className="font-medium">Device</span> means any device
                    that can access the Service such as a computer, a cellphone
                    or a digital tablet.
                  </li>
                  <li>
                    <span className="font-medium">Personal Data</span> is any
                    information that relates to an identified or identifiable
                    individual.
                  </li>
                  <li>
                    <span className="font-medium">Service</span> refers to the
                    advertisement, website, or application.
                  </li>
                  <li>
                    <span className="font-medium">Service Provider</span> means
                    any natural or legal person who processes the data on behalf
                    of the Company. It refers to third-party companies or
                    individuals employed by the Company to facilitate the
                    Service, to provide the Service on behalf of the Company, to
                    perform services related to the Service or to assist the
                    Company in analyzing how the Service is used.
                  </li>
                  <li>
                    <span className="font-medium">Usage Data</span> refers to
                    data collected automatically, either generated by the use of
                    the Service or from the Service infrastructure itself (for
                    example, the duration of a page visit).
                  </li>
                  <li>
                    <span className="font-medium">You</span> means the
                    individual accessing or using the Service, or the company,
                    or other legal entity on behalf of which such individual is
                    accessing or using the Service, as applicable.
                  </li>
                </ul>
              </div>
            </section>

            <section className="space-y-6">
              <h2 className="font-serif text-2xl text-gray-900">
                Collecting and Using Your Personal Data
              </h2>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Types of Data Collected
                </h3>
                <h4 className="mb-2 text-lg font-medium text-gray-900">
                  Personal Data
                </h4>
                <p className="mb-3 text-gray-700">
                  While using Our Service, We may ask You to provide Us with
                  certain personally identifiable information that can be used
                  to contact or identify You. Personally identifiable
                  information may include, but is not limited to:
                </p>
                <ul className="list-disc space-y-2 pl-6 text-gray-700">
                  <li>First name and last name</li>
                  <li>Email address</li>
                  <li>Phone number</li>
                  <li>
                    Location details such as your address, city, or country
                  </li>
                  <li>
                    Any other data such as personal preferences, requirements,
                    or comments
                  </li>
                </ul>
              </div>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Use of Your Personal Data
                </h3>
                <p className="mb-3 text-gray-700">
                  The Company may use Personal Data for the following purposes:
                </p>
                <ul className="list-disc space-y-2 pl-6 text-gray-700">
                  <li>
                    To provide and maintain our Service, including to monitor
                    the usage of our Service.
                  </li>
                  <li>
                    To manage Your Account: to manage Your registration as a
                    user of the Service.
                  </li>
                  <li>
                    For the performance of a contract: the development,
                    compliance and undertaking of the purchase contract.
                  </li>
                  <li>
                    To contact You: To contact You by email, telephone calls,
                    SMS, or other equivalent forms of electronic communication.
                  </li>
                  <li>
                    To provide You with news, special offers and general
                    information about other goods, services and events.
                  </li>
                  <li>
                    To manage Your requests: To attend and manage Your requests
                    to Us.
                  </li>
                  <li>
                    For business transfers: We may use Your information to
                    evaluate or conduct a merger, divestiture, restructuring,
                    reorganization, dissolution, or other sale.
                  </li>
                  <li>
                    For other purposes: We may use Your information for other
                    purposes, such as data analysis, identifying usage trends.
                  </li>
                </ul>
              </div>
            </section>

            <section className="space-y-6">
              <h2 className="font-serif text-2xl text-gray-900">
                Transfer and Disclosure of Your Personal Data
              </h2>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Transfer of Your Personal Data
                </h3>
                <p className="text-gray-700">
                  Your information, including Personal Data, is processed at the
                  Company&apos;s operating offices and in any other places where
                  the parties involved in the processing are located. Your
                  consent to this Privacy Policy followed by Your submission of
                  such information represents Your agreement to that transfer.
                </p>
              </div>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Disclosure of Your Personal Data
                </h3>
                <div className="space-y-4">
                  <div>
                    <h4 className="mb-2 text-lg font-medium text-gray-900">
                      Law enforcement
                    </h4>
                    <p className="text-gray-700">
                      Under certain circumstances, the Company may be required
                      to disclose Your Personal Data if required to do so by law
                      or in response to valid requests by public authorities.
                    </p>
                  </div>

                  <div>
                    <h4 className="mb-2 text-lg font-medium text-gray-900">
                      Other legal requirements
                    </h4>
                    <p className="mb-3 text-gray-700">
                      The Company may disclose Your Personal Data in the good
                      faith belief that such action is necessary to:
                    </p>
                    <ul className="list-disc space-y-2 pl-6 text-gray-700">
                      <li>Comply with a legal obligation</li>
                      <li>
                        Protect and defend the rights or property of the Company
                      </li>
                      <li>
                        Prevent or investigate possible wrongdoing in connection
                        with the Service
                      </li>
                      <li>
                        Protect the personal safety of Users of the Service or
                        the public
                      </li>
                      <li>Protect against legal liability</li>
                    </ul>
                  </div>
                </div>
              </div>
            </section>

            <section className="space-y-6">
              <h2 className="font-serif text-2xl text-gray-900">
                Additional Information
              </h2>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Security of Your Personal Data
                </h3>
                <p className="text-gray-700">
                  The security of Your Personal Data is important to Us, but
                  remember that no method of transmission over the Internet, or
                  method of electronic storage is 100% secure. While We strive
                  to use commercially acceptable means to protect Your Personal
                  Data, We cannot guarantee its absolute security.
                </p>
              </div>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Links to Other Websites
                </h3>
                <p className="text-gray-700">
                  Our Service may contain links to other websites that are not
                  operated by Us. If You click on a third party link, You will
                  be directed to that third party&apos;s site. We strongly
                  advise You to review the Privacy Policy of every site You
                  visit.
                </p>
                <p className="mt-3 text-gray-700">
                  We have no control over and assume no responsibility for the
                  content, privacy policies or practices of any third party
                  sites or services.
                </p>
              </div>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Changes to this Privacy Policy
                </h3>
                <p className="text-gray-700">
                  We may update Our Privacy Policy from time to time. We will
                  notify You of any changes by posting the new Privacy Policy on
                  this page.
                </p>
                <p className="mt-3 text-gray-700">
                  You are advised to review this Privacy Policy periodically for
                  any changes. Changes to this Privacy Policy are effective when
                  they are posted on this page.
                </p>
              </div>

              <div>
                <h3 className="mb-3 font-serif text-xl text-gray-900">
                  Contact Us
                </h3>
                <p className="text-gray-700">
                  If you have any questions about this Privacy Policy, You can
                  contact us via email at{" "}
                  <a
                    href="mailto:tech@gosupersquad.com"
                    className="text-blue-600 transition-colors duration-200 hover:text-blue-800"
                  >
                    tech@gosupersquad.com
                  </a>
                </p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
